title: Tea, Sass, and Chocolate
description: Tea, Sass, and Chocolate
author: Jay / Shirou
logo: ProfileIcon.png
github: "https://github.com/shirou14/TeaSassAndChocolate.github.io.git"
about: Sit with me, drink some tea, let me tell you a thing.
email: Shirou14@hotmail.com

baseurl: ""
url: "https://TeaSassAndChocolate.github.io"

disqus_shortname: Shirou
google_analytics: UA-72862926-1

share:
  twitter_username: shirou14
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
